# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('webapp/templates', 'templates'), ('webapp/static', 'static')],
    hiddenimports=[
        'webview',
        'webview.platforms.qt',
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'portalocker',
        'platformdirs',
        'flask',
        'flask_socketio',
        'flask_sqlalchemy',
        'sqlalchemy',
        'json',
        'pathlib',
        'threading',
        'socket',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='uil-dl',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=False,
    icon='assets/icon.png',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version.txt',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[],
    name='uil-dl',
)
app = BUNDLE(
    coll,
    name='uil-dl.app',
    icon='assets/icon.png',
    bundle_identifier='dev.acemavrick.uil-dl',
    info_plist={
        'CFBundleName': 'UIL-DL',
        'CFBundleDisplayName': 'UIL-DL',
        'CFBundleVersion': '1.0.0-beta',
        'CFBundleShortVersionString': '1.0.0-beta',
        'CFBundleIdentifier': f'dev.acemavrick.uil-dl',
        'NSHumanReadableCopyright': 'Copyright © 2025 acemavrick. Licensed under the MIT License. See github.com/acemavrick/uil-dl',
    },
)
