// type-safe command bindings generated by tauri-specta
use specta::Type;
use tauri_specta::Event;

// re-export for use in commands
pub use specta;
pub use tauri_specta;

// events that can be emitted to frontend
#[derive(Debug, Clone, serde::Serialize, Type, Event)]
pub struct LoadingProgressEvent {
    pub stage: String,
    pub done: bool,
    pub message: Option<String>,
    pub count: Option<u32>,
}

#[derive(Debug, Clone, serde::Serialize, Type, Event)]
pub struct QueueUpdateEvent {
    pub queue: Vec<crate::models::QueueItem>,
    pub active_count: usize,
    pub pending_count: usize,
    pub completed_count: usize,
}

#[derive(Debug, Clone, serde::Serialize, Type, Event)]
pub struct ErrorEvent {
    pub message: String,
    pub details: Option<String>,
}
